### PR TITLE
Stateful properties

### PR DESCRIPTION
**Pull request by keathley**
Adding some stateful property tests. A few API changes needed to be made to accommodate this. I also added specs and dialyzer support. Added oath contracts for some key operations that can't be type checked. Finally, I removed nimble_options because it had breaking API changes and I wasn't happy with how it was behaving.

### CODE REVIEW

**Comment by QuinnWilton** [comment]
Oh this is awesome! For my upcoming `Norm` talk, I was really hoping to mention stateful testing, but I'm starting to worry that it might be outside of the scope of a 30 minute talk that also needs to cover `Norm` + `StreamData` + a few other things, given that `PropEr` is really what you want to be using for stateful testing.

With that being said, do you mind if I point people toward`Mentat` as being a great real-world demonstration of what stateful testing looks like in Elixir?

**Comment by keathley** [comment]
@QuinnWilton Yeah of course :). I was also considering writing up a blog post that talks about the "clock" pattern and how to make "time" more deterministic. Having that knowledge spread around is a good.

**Comment by QuinnWilton** [comment]
Awesome, thank you! It was a little bit like a bat signal seeing a notification pop up on my phone saying a pull request was opened on a project I follow, with "stateful properties" in the name.

That blog post sounds really valuable, but I also think in general the pattern of using `Norm` to specify your options is a really powerful one, in terms of enabling really thorough fuzzing of your code.

**Review by mhanberg — COMMENTED** [review]
LGTM

**Pull request merged**
